template = "https://github.com/giellalt/template-lang-und"
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "toke1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tkl"
__UND2C__ = "tkl"
__UNDEFINED__ = "Tokelauan"
__UND__ = "tkl"
