template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "toke1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tkl"
__UND2C__ = "tkl"
__UNDEFINED__ = "Tokelauan"
__UND__ = "tkl"
